import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { nanoid } from "nanoid";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const Body = z.object({
  cmid: z.string(),
  actionType: z.string(),
  reason: z.string().optional(),
  priority: z.number().default(3),
  dueBy: z.string().optional(),
  linkedMessageId: z.string().optional(),
});

export async function POST(req: Request) {
  const parsed = Body.safeParse(await req.json());
  if (!parsed.success) return NextResponse.json({ error: "잘못된 요청" }, { status: 400 });
  const d = parsed.data;
  const item = await prisma.actionItem.create({
    data: {
      id: nanoid(),
      cmid: d.cmid,
      actionType: d.actionType,
      reason: d.reason,
      priority: d.priority,
      dueBy: d.dueBy ? new Date(d.dueBy) : null,
      linkedMessageId: d.linkedMessageId,
      autoGenerated: true,
      status: "Open",
    },
  });
  return NextResponse.json({ id: item.id });
}
